#!/bin/sh
# Writes the runtime config the production bundle reads from `window.__env`
# and applies BASE_HREF to index.html + nginx.
# Run by nginx's own entrypoint (/docker-entrypoint.d) before nginx starts, so
# the same image can be pointed at any Supabase project - and served under any
# URL path - via env vars.
set -eu

html=/usr/share/nginx/html
target=$html/config.js
base_conf=/etc/nginx/familyfux-base-href.conf

: "${SUPABASE_URL:=}"
: "${SUPABASE_ANON_KEY:=}"
: "${BASE_HREF:=/}"

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "familyfux: SUPABASE_URL and SUPABASE_ANON_KEY must both be set" >&2
    echo "familyfux: (the anon/publishable key is a browser-side value, not a secret)" >&2
    exit 1
fi

# Keep quotes and backslashes from breaking out of the generated string literal.
escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > "$target" <<CONFIG
window.__env = {
  supabaseUrl: "$(escape "$SUPABASE_URL")",
  supabaseAnonKey: "$(escape "$SUPABASE_ANON_KEY")",
};
CONFIG

echo "familyfux: wrote $target for $SUPABASE_URL"

# ---------- BASE_HREF ----------
# Normalise to "/", or "/some/path/" with leading and trailing slash. A full
# URL (https://nas.example/familyfux) is accepted too; only its path is used,
# since the origin is whatever the browser reached us through anyway.
base=$BASE_HREF
case "$base" in
    *://*)
        base=${base#*://}
        case "$base" in
            */*) base=/${base#*/} ;;
            *)   base=/ ;;
        esac
        ;;
esac
case "$base" in /*) ;; *) base=/$base ;; esac
case "$base" in */) ;; *) base=$base/ ;; esac

# Restrict to characters that are safe unquoted in HTML, sed and nginx regex.
case "$base" in
    *[!A-Za-z0-9/._~-]*)
        echo "familyfux: BASE_HREF '$BASE_HREF' contains unsupported characters" >&2
        exit 1
        ;;
esac

# The build emits <base href="/">; the pattern also matches an already
# rewritten value so a container restart re-applies the current env cleanly.
# Not `sed -i`: that needs a temp file next to index.html, and the html
# directory itself is root-owned — only the files in it belong to nginx.
tmp=$(mktemp)
sed "s|<base href=\"[^\"]*\">|<base href=\"$base\">|" "$html/index.html" > "$tmp"
cat "$tmp" > "$html/index.html"
rm -f "$tmp"

if [ "$base" = / ]; then
    cat > "$base_conf" <<NGINX
# BASE_HREF is "/": nothing to strip. Generated by 30-familyfux-config.sh.
NGINX
else
    prefix=${base%/}
    prefix_re=$(printf '%s' "$prefix" | sed 's/[.]/\\./g')
    cat > "$base_conf" <<NGINX
# Generated by 30-familyfux-config.sh from BASE_HREF=$BASE_HREF.
# Serve the bundle under $base as well as under /, so it works whether or not
# the reverse proxy strips the prefix before forwarding.
location = $prefix {
    return 301 $base;
}
rewrite ^$prefix_re/(.*)\$ /\$1;
NGINX
fi

echo "familyfux: base href is $base"
